---
version: "3.9"
services:
  run_tests:
    image: cq.jwt-compress
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PYTHON_VER=${PYTHON_VER:-3.11.10}
    mem_limit: 1g
    cpus: 1
